
name: Build & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: AzureChinaCloud
    - name: Build image on ACR
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          az configure --defaults acr=${{ vars.AZURE_CONTAINER_REGISTRY }}
          az acr build -t  ${{ vars.REGISTRY_URL }}/cpuload:${{ github.sha }} .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: AzureChinaCloud
    - name: Set up Kubeconfig
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ vars.AKS_CLUSTER_NAME }}
        resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
    - name: Replace image in deployment file and deploy to AKS
      run: |
        IMAGE_PATH="${{ vars.REGISTRY_URL }}/cpuload:${{ github.sha }}"
        sed -i "s|image:.*|image: $IMAGE_PATH|" deployment.yml
        cat deployment.yml
        kubectl apply -f deployment.yml
        kubectl rollout status deployment/cpuload
